"""Source Adapter Fuzz public API."""

from .adapters import HttpAdapter, SourceAdapter, Strategy
from .cache import CacheEntry, MemoryCache, deduplicate_urls, normalize_cache_key
from .engine import AcquisitionEngine
from .errors import (
    AcquisitionError,
    AcquisitionFailed,
    AdapterContractError,
    CancelledAttempt,
    CharsetFailure,
    ClientFailure,
    ContinuationError,
    EmptyResponse,
    ErrorDisposition,
    Forbidden,
    InvalidRequest,
    JavaScriptShell,
    MalformedPDF,
    NetworkFailure,
    PartialBatchFailure,
    RateLimited,
    RedirectLoop,
    ResponseTimeout,
    ServerFailure,
    StaleCache,
    TerminalError,
    TooManyRedirects,
    TruncatedBody,
    UnexpectedContentType,
)
from .fixtures import FixtureServer
from .models import (
    AcquisitionReceipt,
    AcquisitionRequest,
    AcquisitionRun,
    AdapterResult,
    AttemptReceipt,
    AttemptState,
    BatchItem,
    BatchResult,
)
from .reporting import ConformanceRecord, render
from .scenarios import SCENARIOS, list_scenarios, run_scenarios, run_url

__all__ = [
    "AcquisitionEngine",
    "AcquisitionError",
    "AcquisitionFailed",
    "AcquisitionReceipt",
    "AcquisitionRequest",
    "AcquisitionRun",
    "AdapterContractError",
    "AdapterResult",
    "AttemptReceipt",
    "AttemptState",
    "BatchItem",
    "BatchResult",
    "CacheEntry",
    "CancelledAttempt",
    "CharsetFailure",
    "ClientFailure",
    "ConformanceRecord",
    "ContinuationError",
    "EmptyResponse",
    "ErrorDisposition",
    "FixtureServer",
    "Forbidden",
    "HttpAdapter",
    "InvalidRequest",
    "JavaScriptShell",
    "MalformedPDF",
    "MemoryCache",
    "NetworkFailure",
    "PartialBatchFailure",
    "RateLimited",
    "RedirectLoop",
    "ResponseTimeout",
    "SCENARIOS",
    "ServerFailure",
    "SourceAdapter",
    "StaleCache",
    "Strategy",
    "TerminalError",
    "TooManyRedirects",
    "TruncatedBody",
    "UnexpectedContentType",
    "deduplicate_urls",
    "list_scenarios",
    "normalize_cache_key",
    "render",
    "run_scenarios",
    "run_url",
]

__version__ = "0.1.0"
